name: Build CPD-Client Mac

on:
  workflow_dispatch:

jobs:
  build:
    name: Build CPD-Client Mac
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: macos-latest

    steps:

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Python install setuptools
        run: python3 -m pip install setuptools

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Make and Publish
        run: npm run build-mac
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}