name: Build CPD-Client Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    name: Build CPD-Client Ubuntu
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Install flatpak
        run: |
          sudo apt-get install flatpak -y
          sudo apt-get install flatpak-builder -y
          sudo apt-get install elfutils -y
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.freedesktop.Platform/x86_64/22.08 org.freedesktop.Sdk/x86_64/22.08 org.electronjs.Electron2.BaseApp/x86_64/22.08 -y
          git config --global --add protocol.file.allow always

      - name: Make and Publish
        run: npm run build-linux
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}